baseURL = "https://micsthepick.github.io/blog/"
languageCode = "en-us"
title = "micsthepick's blog"
theme = "minimal"
publishDir = "../docs"

[params]
    author = "Michael Pannekoek"
    description = "Personal blog - powered by Hugo"
    githubUsername = "micsthepick"
    accent = "#FFAA00"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["python", "javascript", "css", "lisp"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/micsthepick/"
    name = "fab fa-github"
    weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/in/michael-pannekoek-007b63104/"
    name = "fab fa-linkedin"
    weight = 2

[[menu.icon]]
    url = "https://stackoverflow.com/users/4678667/micsthepick"
    name = "fab fa-stack-overflow"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true